version: '3.8'
services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "3002:3001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/proxy
      - IS_NEW=false
      - TEST_CONCURRENCY=25
    depends_on:
      - mongo

  mongo:
    external: true
    name: my-mongo
